services:
  - type: web
    name: frontend-service
    env: static
    buildCommand: npm run build
    startCommand: nginx -g 'daemon off;'
    dockerfilePath: docker/frontend/Dockerfile
    contextPath: ./frontend
    envVars:
      - key: VITE_API_URL
        value: http://localhost:8000/api
      - key: VITE_WS_URL
        value: ws://localhost:8000/ws
    ports:
      - port: 80

  - type: web
    name: backend-service
    env: python
    dockerfilePath: docker/backend/Dockerfile
    contextPath: ./Backend
    startCommand: python src/run.py
    envVars:
      - key: DATABASE_URL
        value: sqlite:///app/data/db/neverhack.db
    ports:
      - port: 8000
    disk:
      name: app-data
      mountPath: /app/data
