version: '3.8'

services:
  backend:
    build:
      context: ../
      dockerfile: docker/backend/Dockerfile
    volumes:
      - ../Backend/logs:/app/logs
    environment:
      - HOST=0.0.0.0
      - PORT=10000
    ports:
      - "10000:10000"

  frontend:
    build:
      context: ../
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - ../frontend/dist:/usr/share/nginx/html
    ports:
      - "80:80"