version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:8000/api
      - VITE_WS_URL=ws://localhost:8000/ws
    depends_on:
      - backend

  backend:
    build:
      context: ../Backend
      dockerfile: ../docker/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../Backend/data:/app/data
      - ../Backend/logs:/app/logs
    environment:
      - DATABASE_URL=sqlite:///app/data/db/neverhack.db